# Generated by Django 3.2.5 on 2021-07-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nome'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='elogio',
            options={'ordering': ['-data'], 'verbose_name': 'Elogio', 'verbose_name_plural': 'Elogios'},
        ),
        migrations.AlterModelOptions(
            name='emailresponsaveis',
            options={'ordering': ['nome'], 'verbose_name': 'Cadastro de e-mail dos responsáveis', 'verbose_name_plural': 'Cadastro de e-mail dos responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['nome', 'cidade'], 'verbose_name': 'Filial', 'verbose_name_plural': 'Filiais'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='motivo',
            options={'ordering': ['nome'], 'verbose_name': 'Motivo', 'verbose_name_plural': 'Motivos'},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['-data'], 'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.CreateModel(
            name='EmailNaoEntregue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=20)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
            ],
            options={
                'verbose_name': 'E-mail não entregue',
                'verbose_name_plural': 'E-mails não entregues',
                'ordering': ['-data'],
            },
        ),
    ]
