# Generated by Django 3.2.5 on 2021-07-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210716_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnaoentregue',
            name='retorno',
            field=models.TextField(default='Não informado'),
            preserve_default=False,
        ),
    ]
