# Generated by Django 3.2.5 on 2021-07-20 10:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailnaoentregue_retorno'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ocorrencia',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
    ]
