# Generated by Django 3.2.5 on 2021-07-08 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_cargo_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elogio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('alteracao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateField()),
                ('observacao', models.TextField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elogios', to='core.funcionario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
