# Generated by Django 3.2.5 on 2021-07-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_elogio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivo',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'ordering': ['data']},
        ),
    ]
