# Generated by Django 3.2.5 on 2021-07-20 11:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ocorrencia_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cargo',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='elogio',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='emailnaoentregue',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='emailresponsaveis',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='filial',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='motivo',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
    ]
