# Generated by Django 3.2.5 on 2021-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailresponsaveis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailresponsaveis',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
