# Generated by Django 3.2.5 on 2021-07-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailnaoentregue_ativo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cargo',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='elogio',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='emailnaoentregue',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='emailresponsaveis',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='filial',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='motivo',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ocorrencia',
            managers=[
            ],
        ),
    ]
