# Generated by Django 3.2.5 on 2021-07-20 11:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='perfil',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
    ]
