# Generated by Django 3.2.5 on 2021-07-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_ativo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='perfil',
            managers=[
            ],
        ),
    ]
