# Generated by Django 3.2.5 on 2021-07-13 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('alteracao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('veiculo', models.CharField(blank=True, max_length=255, null=True)),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('alteracao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('endereco_cliente', models.CharField(max_length=255)),
                ('numero_pedido', models.CharField(max_length=255)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saida_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('recebimento_pedido', models.DateTimeField(blank=True, null=True)),
                ('detalhes_pedido', models.TextField(blank=True, null=True)),
                ('observacao_final', models.TextField(blank=True, null=True)),
                ('entregador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entregas.entregador')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario_recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_recebimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['saida_pedido'],
            },
        ),
    ]
