# Generated by Django 3.2.5 on 2021-07-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_entrega_filial_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='saida_pedido',
            field=models.DateTimeField(),
        ),
    ]
