# Generated by Django 3.2.5 on 2021-07-20 11:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0003_alter_entrega_saida_pedido'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entrega',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='entregador',
            managers=[
                ('is_active', django.db.models.manager.Manager()),
            ],
        ),
    ]
