# Generated by Django 3.2.5 on 2021-07-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0004_auto_20210720_0809'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entrega',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='entregador',
            managers=[
            ],
        ),
    ]
